' Gambas module file

'
' Konvertilo
' Conversor y manipulador de archivos
'
' Copyright (C) Martín Belmonte
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'

Public Function FileDelibery(strTool As String, strPath As String, Optional intPage As Integer) As String '' Funcion que reparte el archivo a una funcion coincidente con el nombre de la herramienta "Tool" en el segundo parametro

  Dim str As String

  str = "0"

  Select strTool
      'General
    Case "File-Rename" 'Renombrador de archivos

    Case "File-Check" 'Verificador de nombre de archivo

      '## JPEG
    Case "JPEG>Email" 'Crea copias reducidas en un directorio temporal y las adjunta en un nuevo email.
      'str = JPEGEmail(strPath)

    Case "JPEG>GIFEmail" 'Crea un archivo GIF y lo adjunta en un nuevo email.
      str = JPEGGIFEmail(strPath)

    Case "JPEG>Copy-Reduced-Color" 'Crea una copia reducida en la misma ubicación que la original
    Case "JPEG>Copy-Reduced-Gray" 'Crea una copia reducida en escala de grices en la misma ubicación que la original
    Case "JPEG>Copy-Gray" 'Crea una copia en escala de grices en la misma ubicación que la original
    Case "JPEG>Square" 'Crea una copia reducida de proporción cuadrada en la misma ubicación que la original.
    Case "JPEG>PDF" 'Crea un archivo PDF con todas las imagenes que se le pase.
      str = JPEGPDF(strPath, intPage)

    Case "JPEG>Arrange" 'Mueve las fotografias organizandolas según su fecha de captura.
      str = JPEGArrange(strPath)

      '## PNG
    Case "PNG>Copy-Reduced-Color" 'Crea una copia reducida en la misma ubicación que la original
    Case "PNG>JPEG-Copy-Reduced-Color" 'Crea una copia reducida en la misma ubicación que la original
      str = PNGJPEGReduced(strPath)

      '## ODT
    Case "ODT-Thumbnail" 'Extractor de miniatura del documento
    Case "ODT>EPUB" 'Convertir documentos ODT en documentos EPUB

      '##PDF
    Case "PDF>Decrypt" 'Crea una copia desencriptada del archivo.
      str = PDFDecrypt(strPath)

    Case "PDF>Image" 'Extractor de paginas en formato de imagen jpeg una imagen por página.
      str = PDFImage(strPath, intPage)

    Case "PDF>PDF-R90" 'Rota las paginas 90 grados.
      str = PDFR90(strPath)

    Case "PDF>Pages" 'Extractor de paginas en formato pdf

    Case "PDF>OCR-Text" 'Extractor de paginas en formato de imagen TIF y reconocimiento optico de caracteres
      str = PDFOCRText(strPath)

      '## Video
    Case "Video>Frame" 'Extractor de fotograma de un video

      '## MDB, ACCDB
    Case "JET>SQL" 'Crea los archivos SQL necesarios para reconstruir una base de datos Jet en SQLite, PostgreSQL y MySQL

  End Select

  Return str

End

Public Function JPEGArrange(strPath As String) As String '' Devuelve la rutade destino del archivo

  Dim stxExif As New String[]

  Dim strTimeStamp As String
  Dim strYear As String
  Dim strMonth As String
  Dim strDay As String
  Dim strTime As String
  Dim strMnfr As String
  Dim strModel As String
  Dim strCRC As String

  Dim prs As Process

  Dim strRenPath As String
  Dim intEx As Integer

  strCRC = MUtility.CRC32(strPath)

  If MStarter.strState = "running" Then

    ' Extacción de un sobconjunto de metadatos de la foto
    stxExif = MUtility.ExifRaw(strPath)
    For intEx = 0 To stxExif.Max
      Select Split(stxExif[intEx], "\t")[0]
        Case "DateTimeOriginal"
          strTimeStamp = Split(stxExif[intEx], "\t")[1]
          strTimeStamp = MValidator.OnlyNumbers(strTimeStamp)
          strTimeStamp = String.Mid(strTimeStamp, 1, 14)

          strYear = String.Mid(strTimeStamp, 1, 4)
          strMonth = String.Mid(strTimeStamp, 5, 2)
          strDay = String.Mid(strTimeStamp, 7, 2)
          strTime = String.Mid(strTimeStamp, 9, 6)

        Case "Make"
          strMnfr = Split(stxExif[intEx], "\t")[1]
          strMnfr = String.UCase(strMnfr)

        Case "Model"
          strModel = Split(stxExif[intEx], "\t")[1]
          strModel = MValidator.NoSymbols(strModel)
          strModel = String.UCase(strModel)

      End Select
    Next

    If Not Exist(User.Home &/ strYear & "F" &/ strMonth) Then ' Verificación de la existencia de la carpeta
      Shell "mkdir -p " & User.Home &/ strYear & "F" &/ strMonth
    Endif
    If String.Len(strTimeStamp) = 14 Then
      If String.Len(strCRC) = 8 Then
        strRenPath = User.Home &/ strYear & "F" &/ strMonth &/ strTimeStamp & "-" & strMnfr & "-" & strModel & "-" & strCRC & ".JPEG"
        If Exist(strRenPath) = False Then
          prs = Shell "mv '" & strPath & "' " & strRenPath
          While
            prs.State = prs.Running
            Wait 0.05
          Wend
        Endif
      Endif
    Endif

  Endif
  If Exist(strRenPath) Then
    If Stat(strRenPath).Type = gb.File Then
      Return strRenPath
    Else
      Return "0"
    Endif
  Endif

End

Public Function JPEGGIFEmail(strPath As String) As String ''Si el archivo es procesado satisfactoriamente se devuelve la ruta de este.

  Dim stxExif As New String[]

  Dim strTimeStamp As String
  Dim strYear As String
  Dim strMonth As String
  Dim strDay As String
  Dim strHour As String
  Dim strMin As String
  Dim strSec As String
  Dim strCRC As String

  Dim prs As Process

  Dim strRenPath As String
  Dim intEx As Integer
  Dim strCommand As String

  strCRC = MUtility.CRC32(strPath)

  If MStarter.strState = "running" Then

    ' Extacción de un sobconjunto de metadatos de la foto
    stxExif = MUtility.ExifRaw(strPath)
    For intEx = 0 To stxExif.Max
      Select Split(stxExif[intEx], "\t")[0]
        Case "DateTimeOriginal"
          strTimeStamp = Split(stxExif[intEx], "\t")[1]
          strTimeStamp = MValidator.OnlyNumbers(strTimeStamp)
          strTimeStamp = String.Mid(strTimeStamp, 1, 14)

          strYear = String.Mid(strTimeStamp, 1, 4)
          strMonth = String.Mid(strTimeStamp, 5, 2)
          strDay = String.Mid(strTimeStamp, 7, 2)
          strHour = String.Mid(strTimeStamp, 9, 2)
          strMin = String.Mid(strTimeStamp, 11, 2)
          strSec = String.Mid(strTimeStamp, 13, 2)

      End Select
    Next

    If Not Exist(User.Home &/ strYear & "F" &/ "email") Then ' Verificación de la existencia de la carpeta
      Shell "mkdir -p " & User.Home &/ strYear & "F" &/ "email"
    Endif
    If String.Len(strTimeStamp) = 14 Then
      If String.Len(strCRC) = 8 Then
        strRenPath = User.Home &/ strYear & "F" &/ "email" &/ strTimeStamp & "-" & strCRC & "-RC.JPEG"

        If Exist(strRenPath) = False Then
          prs = Shell "cp '" & strPath & "' " & strRenPath
          strCommand = "convert -thumbnail 1200x675 -compress jpeg -quality 75 -enhance"
          strCommand &= " " & strPath & " " & strRenPath
          prs = Shell strCommand
          While
            prs.State = prs.Running
            Wait 0.05
          Wend
        Endif
      Endif
    Endif

  Endif
  If Exist(strRenPath) Then
    If Stat(strRenPath).Type = gb.File Then
      Return strRenPath
    Else
      Return "0"
    Endif
  Endif

End

Public Function JPEGPDF(strPath As String) As String ''Convierte todas las imágenes JPEG de la lista en un archivo PDF. Si el archivo PDF es creado satisfactoriamente se devuelve la ruta del mismo.

  'Dim prs As Process
  'Dim strCommand As String

  Dim prs2 As Process
  Dim strCommand2 As String

  'Dim strTmpPath As String
  Dim strRenPath As String

  If MStarter.strState = "running" Then

    'strTmpPath = File.Dir(strPath) &/ String.LCase(File.BaseName(strPath)) & "#rezised" & "." & String.LCase(File.Ext(strPath))
    strRenPath = File.Dir(strPath) &/ String.LCase(File.BaseName(strPath)) & ".pdf"

    'If Exist(strRenPath) = False Then
    'strCommand = "mogrify -resize 1754x2481! " & strPath
    'prs = Shell strCommand
    'While
    '  prs.State = prs.Running
    '  Wait 0.05
    'Wend

    'Endif

    'strCommand2 = "convert -type grayscale -quality 30 " & strPath & " " & strRenPath
    strCommand2 = "convert -quality 30 " & strPath & " " & strRenPath
    prs2 = Shell strCommand2
    While
      prs2.State = prs2.Running
      Wait 0.05
    Wend

    ' If Exist(strTmpPath) Then
    '   Kill strTmpPath
    ' Endif

  Endif

  If Exist(strRenPath) Then
    If Stat(strRenPath).Type = gb.File Then
      Return strRenPath
    Else
      Return "0"
    Endif
  Endif

End

Public Function PNGJPEGReduced(strPath As String) As String '' Devuelve la ruta al archivo jpeg creado

  Dim prs As Process

  Dim strRenPath As String
  Dim strCommand As String

  If MStarter.strState = "running" Then

    strRenPath = File.Dir(strPath) &/ String.LCase(File.BaseName(strPath)) & "-rc.jpeg"

    If Exist(strRenPath) = False Then

      strCommand = "convert -compress jpeg -quality 75 -enhance"
      strCommand &= " " & strPath & " " & strRenPath
      prs = Shell strCommand
      While
        prs.State = prs.Running
        Wait 0.05
      Wend
    Endif
  Endif

  If Exist(strRenPath) Then
    If Stat(strRenPath).Type = gb.File Then
      Return strRenPath
    Else
      Return "0"
    Endif
  Endif

End

Public Function PDFDecrypt(strPath As String) As String '' Devuelve la ruta al archivo desencriptado

  Dim strName As String
  Dim strCommand As String
  Dim prsCommand As Process

  strName = File.Dir(strPath) &/ File.BaseName(strPath) & "-dcr.pdf"
  strCommand = "gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile='" & strName & "' -c .setpdfwrite -f '" & strPath & "'"

  prsCommand = Shell strCommand

  While prsCommand.State = prsCommand.Running
    Wait 0.05
  Wend

  If Exist(strName) Then

    If Stat(strName).Type = gb.File Then
      Return strName
    Else
      Return "0"
    Endif
  Endif

End

Public Function PDFImage(strPath As String, intPage As Integer) As String '' Devuelve la carpeta donde se extrajeron las imagenes

  Dim strCommand As String
  Dim prs1 As Process
  Dim pdf As New PdfDocument
  'Dim index As Integer
  Dim strNameNoExt As String
  Dim strNumx As String
  Dim strPageImageName As String
  Dim int As Integer

  strNameNoExt = String.Left(strPath, String.RInStr(strPath, ".") - 1)
  int = 0

  pdf.Open(strPath)
  If Exist(strNameNoExt) = False
    Shell "mkdir -p '" & strNameNoExt & "'"
  Endif

  'For index = 0 To pdf.Count - 1

  If MStarter.strState = "running" Then

    Select String.Len(Str(intPage + 1)) ' Le sumo 1 porque convert arranca de 0
      Case 1
        strNumx = "s00" & Str(intPage + 1) '' idem
      Case 2
        strNumx = "s0" & Str(intPage + 1) '' idem
      Case 3
        strNumx = "s" & Str(intPage + 1) '' idem
    End Select

    strPageImageName = strNameNoExt &/ strNumx & ".jpeg"

    ' Salia con fondo negro asi que le pude "-alpha remove" y solucionado
    strCommand = "convert -alpha remove -density 300 -resample 300x300 -quality 30 '" & strPath & "'[" & intPage & "] '" & strPageImageName & "'"
    'strCommand = "convert -type grayscale -density 300 -resample 300x300 -quality 30 '" & strPath & "'[" & index & "] '" & strPageImageName & "'"

    prs1 = Shell strCommand

    While prs1.State = prs1.Running
      Wait 0.05
    Wend

    If Exist(strPageImageName) Then
      If Stat(strPageImageName).Type = gb.File Then
        Inc int
      Endif
    Endif

  Endif

  'Next

  'Desktop.Open(strNameNoExt) ' Abrir el directorio donde se estrajerosn las paginas
  'If int = pdf.Count Then
  If Exist(strPageImageName) Then
    Return strPageImageName 'strNameNoExt
  Else
    Return "0"
  Endif

End

Public Function PDFOCRText(strPath As String) As String '' Devuelve la carpeta donde se extrajeron las imagenes PNG

  Dim strCommand As String
  Dim prs1 As Process
  Dim pdf As New PdfDocument
  Dim index As Integer
  Dim strNameNoExt As String
  Dim strNumx As String
  Dim strPageImageName As String
  Dim int As Integer
  'Dim strTxt As String
  Dim strTxtTemp As String

  strNameNoExt = String.Left(strPath, String.RInStr(strPath, ".") - 1)
  int = 0

  pdf.Open(strPath)
  If Exist(strNameNoExt) = False
    Shell "mkdir -p '" & strNameNoExt & "'"
  Endif

  For index = 0 To pdf.Count - 1

    If MStarter.strState = "running" Then

      Select String.Len(Str(index + 1)) ' Le sumo 1 porque convert arranca de 0
        Case 1
          strNumx = "s00" & Str(index + 1) '' idem
        Case 2
          strNumx = "s0" & Str(index + 1) '' idem
        Case 3
          strNumx = "s" & Str(index + 1) '' idem
      End Select

      strPageImageName = strNameNoExt &/ strNumx & ".png"

      strCommand = "convert -alpha remove -density 300 -resample 300x300 -quality 30 '" & strPath & "'[" & index & "] '" & strPageImageName & "'"

      prs1 = Shell strCommand

      While prs1.State = prs1.Running
        Wait 0.05
      Wend

      If Exist(strPageImageName) Then
        If Stat(strPageImageName).Type = gb.File Then
          strTxtTemp = ""

          strCommand = "tesseract '" & strPageImageName & "' stdout -l spa 2>&1"
          Shell strCommand To strTxtTemp
          MStarter.strOCRTxt &= strTxtTemp

          ' Guardado incremental con cada p ágina procesada, al final del proceso este archivo y el final deben coincidir

          File.Save(File.Dir(strPath) &/ File.BaseName(strPath) & "-tmp.txt", MStarter.strOCRTxt)

          'Kill strPageImageName

          Inc int
        Endif
      Endif

    Endif

  Next

  If MStarter.strOCRTxt <> "" Then
    Return MStarter.strOCRTxt
  Else
    Return "0"
  Endif

End

Public Function PDFImageBW(strPath As String) As String '' Extrae la imagenes del PDF en formato JPEG en Escala de grises. Devuelve la carpeta donde se extrajeron las imagenes

  Dim strCommand As String
  Dim prs1 As Process
  Dim pdf As New PdfDocument
  Dim index As Integer
  Dim strNameNoExt As String
  Dim strNumx As String
  Dim strPageImageName As String
  Dim int As Integer

  strNameNoExt = String.Left(strPath, String.RInStr(strPath, ".") - 1)
  int = 0

  pdf.Open(strPath)
  If Exist(strNameNoExt) = False
    Shell "mkdir -p '" & strNameNoExt & "'"
  Endif

  For index = 0 To pdf.Count - 1

    If MStarter.strState = "running" Then

      Select String.Len(Str(index + 1)) ' Le sumo 1 porque convert arranca de 0
        Case 1
          strNumx = "s00" & Str(index + 1) '' idem
        Case 2
          strNumx = "s0" & Str(index + 1) '' idem
        Case 3
          strNumx = "s" & Str(index + 1) '' idem
      End Select

      strPageImageName = strNameNoExt &/ strNumx & ".jpeg"

      strCommand = "convert -density 300 -resample 300x300 -type Grayscale -depth 8 -normalize -level 25%,75%,0.8 '" & strPath & "'[" & index & "] '" & strPageImageName & "'"

      prs1 = Shell strCommand

      While prs1.State = prs1.Running
        Wait 0.05
      Wend

      If Exist(strPageImageName) Then
        If Stat(strPageImageName).Type = gb.File Then
          Inc int
        Endif
      Endif

    Endif

  Next

  Desktop.Open(strNameNoExt) ' Abrir el directorio donde se estrajerosn las paginas
  If int = pdf.Count Then
    Return strNameNoExt
  Else
    Return "0"
  Endif

End

Public Function PDFR90(strPath As String) As String '' Rota las paginas 90 grados

  Dim strName As String
  Dim strCommand As String
  Dim prsCommand As Process

  strName = File.Dir(strPath) &/ File.BaseName(strPath) & "-r90.pdf"

  strCommand = "pdftk A=" & strPath & " cat A1-endeast output " & strName

  prsCommand = Shell strCommand

  While prsCommand.State = prsCommand.Running
    Wait 0.05
  Wend

  If Exist(strName) Then

    If Stat(strName).Type = gb.File Then
      Return strName
    Else
      Return "0"
    Endif
  Endif

End
