' Gambas module file

'
' Konvertilo
' Conversor y manipulador de archivos
'
' Copyright (C) Martín Belmonte
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'

Public stxProgram As New String[] ''<ul><li>0 Database Engine</li><li>1 Database Host</li><li>2 Database Name</li><li>3 Database Path</li><li>4 Language input 2 leters</li><li>5 Language input 3 leters</li><li>6 Language input english</li><li>7 Language input dictionary </li><li>8 Language output 2 leters</li><li>9 Language output 3 leters</li><li>10 Language output english</li><li>11 Language output dictionary </li><li>12 Dimensiones de la ventana del programa </li><li>13 Reserva</li><li>14 Ancho de controles por defecto</li><li>15 Reserva</li><li>16 Show-Filter-Bar [yes,no]</li><li>17 Show-Order-Bar [yes,no]</li><li>18 Mensajes centralizados]</li></ul>
Public strAppPath As String

Public stxDBEngines As New String[] ' Motores de bases de datos soportadas por gambas
Public conProgram As New Connection ' Conexión a la base de datos

Public stxTables As New String[] ' Lista de tablas
Public stxTableFields As New String[][] 'Lista de campos de las tablas

Public stxViews As New String[] ' Lista de vistas
Public stxViewFields As New String[][] 'Lista de campos de las vistas

Public stxTitles As New String[][] 'Lista de títulos de los campos de las vistas y de las tablas

Public stxHeaders As New String[] '' <ul><li>0 Acronimo de dos letras "es"</li><li>1 Acronimo de tres letras "spa"</li><li>2 Nombre en inglés "Spanish"</li><li>3 Nombre nativo "Español"</li><li>4 Grupo del idioma "Indo-European"</li><li>5 Alfabeto "Latn" (latino)</li><li>6 Traducir [True/False]</li></ul>

Public stxFieldsTableCurrentrent As New String[] ' lista de campos para crear los botones de filtros
Public stxFieldsViewCurrentrent As New String[] ' lista de campos para crear los botones de filtros

Public resProgram As Result

Public strInputLanguage As String

'## variables del konvertilo ##
Public stxFiles As New String[] ' Lista de archivos a procesar
Public stxFilesPages As New String[] ' Lista de paginas de cada archivo a procesar cada item es una cadena de texto formada con "1" y/o "0"
'donde 0 es para la pagina que no se procesa y 1 para la que si. ej: "1111110" un archivo con 7 páginas donde la ultima no se procesará.

Public stxExt As New String[] ' Lista de tipode extensiones
Public stxToolsName As New String[] ' Lista de herramientas a aplicar cuando se procesan archivos
Public stxToolsDesc As New String[] ' Lista de descripciones de las herramientas (traducibles)
Public stxToolsExt As New String[] ' Llista de las extensiones de archivo a las que se puede aplicar cada herramienta
Public intTimer As Integer ' Tiempo en segundos transcurridos desde el inicio del procesado de archivos

Public strState As String ' Estado de actividad del programa "running / stopped"
Public stxFilesPlay As New String[] ' Lista de tipos de archivos a procesar txt, pdf etc.
Public stxSchedule As New String[] ' Lista de [Herramienta "\t" Página "\t" Archivo]
Public stxPages As New Integer[] ' Lista de paginas a procesar de un archivo dado, es una matriz temporal den un solo uso.

Public stxEmail As New String[] ' Lista de ruta de imagenes para pasar al gif del correo.
Public stxPDF As New String[] ' Lista de ruta de imagenes para agregar al PDF.
Public stxErr As New String[] ' Lista de rutas de archivos con error Tool/file

Public strOCRTxt As String ' Texto de salida del OCR
Public strOCRFile As String ' Archivo de salida del OCR

Public Sub Main()

  Dim stxPackages As New String[]
  Dim strSQL As String
  Dim resSQL As Result
  Dim intTable As Integer
  Dim strTableTmp As String
  Dim strDBName As String
  Dim stxTmp As New Variant[][]
  Dim intTmp As Integer
  Dim intP As Integer

  strInputLanguage = ""

  strAppPath = User.Home &/ "." & Application.Name
  stxDBEngines = MUtility.FileLoad("engines.txt") ' Motores de bases de datos soportados por gambas

  ' Existencia de directorio de la aplicacion en el directorio home. Esto se ejecutara una unica vez.
  ' Aqui se pueden agregar mas comprobaciones de este tipo para copia de archivos de configuracion y demas cosas similares
  If Exist(strAppPath) = False Then
    Mkdir strAppPath
  Endif
  Wait 0.05
  If Exist(strAppPath &/ "README.md") = False Then
    Copy "README.md" To strAppPath &/ "README.md"
  Endif

  ' Estado de las dependencias.//////////////////////////////////////////////////////////////////////
  stxPackages = MUtility.FileLoad("depend.txt")
  If stxPackages.Count > 0 Then
    Msys.PkgDep(stxPackages)
  Endif

  ' Carga de los parametros del prgrama 1º pasada gb.settings./////////////////////////
  strDBName = Replace(Application.Name & ".sqlite", "-", "")
  stxProgram = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]

  stxProgram[18] = ("Carga de parámetros primera pasada")

  stxProgram[0] = Settings["Program/Database-Engine", "sqlite3"]
  stxProgram[1] = Settings["Program/Database-Host", strAppPath]
  stxProgram[2] = Settings["Program/Database-Name", strDBName]
  stxProgram[3] = Settings["Program/Database-Path", strAppPath &/ strDBName]
  stxProgram[4] = Settings["Program/Language-Input", "es"]
  stxProgram[5] = Settings["Program/Language-Input3", "spa"]
  stxProgram[6] = Settings["Program/Language-InputEng", "spanish"]
  stxProgram[7] = Settings["Program/Language-InputDict", "spanish"]

  stxProgram[8] = Settings["Program/Language-Output", "en"]
  stxProgram[9] = Settings["Program/Language-Output3", "eng"]
  stxProgram[10] = Settings["Program/Language-OutputEng", "english"]
  stxProgram[11] = Settings["Program/Language-OutputDict", "british"]

  ' Existencia de la base de datos.////////////////////////////////////////////////////
  stxProgram[18] = ("Conectando la base de datos")
  conProgram = MData.DBSqlite(stxProgram, "enmpty") ' Si la base de datos no existe se crea una nueva
  conProgram.Name = stxProgram[2]
  conProgram.Open

  ' Analisis de la base de datos.////////////////////////////////////////////////////

  ' LoadTitles() ' Carga de los títulos de los campos
  '
  stxTables.Clear
  stxTables.Insert(MData.getTables(conProgram, "table")) ' Lista de TABLAS

  stxTableFields.Clear
  For intTable = 0 To stxTables.Max
    strTableTmp = stxTables[intTable]
    strSQL = "select * from " & strTableTmp
    resSQL = conProgram.Exec(strSQL)

    stxTmp.Clear
    stxTmp.Insert(MData.getFields(conProgram, strTableTmp, "table", stxTitles))

    For intTmp = 0 To stxTmp.Max
      stxTableFields.Add(stxTmp[intTmp])
    Next
  Next
  'Print "###Tablas ###"
  For intP = 0 To stxTableFields.Max
    Print stxTableFields[intP].Join(":")
  Next

  ' Carga de los parametros del prgrama 2º pasada SQL //////////////////////////////

  'stxProgram[5] = 'MData.SqlMake(stxProgram[4], stxViewFields)
  stxProgram[12] = Settings["Program/Window", "small"]
  stxProgram[13] = Settings["Program/Dict-Path", strAppPath &/ "dict"]
  stxProgram[14] = Settings["Program/Default-width", "120"]

  ' Desde donde se esta ejecutando la aplicación
  Select MUtility.WhereRun()

    Case 0
      stxProgram[9] = "gambas"
    Case 1
      stxProgram[9] = "ide"

  End Select

  '
  stxProgram[18] = ("Cargando lista de idiomas")
  ' Apertura del formulario principal
  '///////////////// Bloque particular
  stxHeaders.Clear
  LoadHeaders()

  stxToolsName.Clear
  stxToolsDesc.Clear
  stxToolsExt.Clear

  LoadTools()

  strState = "stopped"
  stxFilesPlay.Clear
  stxSchedule.Clear

  '//////////////////////////////////

  stxProgram[18] = ("Abriendo formulario principal")

  If conProgram.Opened Then
    FMain.Show()
  Else
    Message.Warning(("No se pudo abrir la conexión a la base de datos"))
  Endif

End

Public Function LoadViews()

  stxViews.Clear
  stxViews.Insert(MData.getTables(conProgram, "view")) ' Lista de VISTAS

End

Public Sub LoadTools() '' Carga de herramientas disponibles para asignar el el proceso de archivos segun su extensión

  '## JPEG
  stxToolsName.Add("JPEG>Email")
  stxToolsDesc.Add(("Crea copias reducidas en un directorio temporal y las adjunta en un nuevo email"))
  stxToolsExt.Add("jpg:jpeg")

  stxToolsName.Add("JPEG>GIFEmail")
  stxToolsDesc.Add(("Crea un archivo") & " GIF " & ("y luego lo adjunta en un nuevo correo") & ".")
  stxToolsExt.Add("jpg:jpeg")

  stxToolsName.Add("JPEG>Copy-Reduced-Color")
  stxToolsDesc.Add(("Crea una copia reducida en la misma ubicación que la original"))
  stxToolsExt.Add("jpg:jpeg")

  stxToolsName.Add("JPEG>Copy-Reduced-Gray")
  stxToolsDesc.Add(("Crea una copia reducida en escala de grices en la misma ubicación que la original"))
  stxToolsExt.Add("jpg:jpeg")

  stxToolsName.Add("JPEG>Copy-Gray")
  stxToolsDesc.Add(("Crea una copia en escala de grices en la misma ubicación que la original"))
  stxToolsExt.Add("jpg:jpeg")

  stxToolsName.Add("JPEG>Square")
  stxToolsDesc.Add(("Crea una copia reducida de proporción cuadrada en la misma ubicación que la original."))
  stxToolsExt.Add("jpg:jpeg")

  stxToolsName.Add("JPEG>PDF")
  stxToolsDesc.Add(("Crea un archivo") & " PDF " & ("con todas las imágenes que se le pase") & ".")
  stxToolsExt.Add("jpg:jpeg")

  stxToolsName.Add("JPEG>Arrange")
  stxToolsDesc.Add(("Mueve las fotografiás organizándolas según su fecha de captura."))
  stxToolsExt.Add("jpg:jpeg")

  '## PNG
  stxToolsName.Add("PNG>Copy-Reduced-Color")
  stxToolsDesc.Add(("Crea una copia reducida en la misma ubicación que la original"))
  stxToolsExt.Add("png")

  stxToolsName.Add("PNG>JPEG-Copy-Reduced-Color")
  stxToolsDesc.Add(("Crea una copia reducida en la misma ubicación que la original"))
  stxToolsExt.Add("png")

  '## ODT
  stxToolsName.Add("ODT-Thumbnail")
  stxToolsDesc.Add(("Extractor de miniatura del documento"))
  stxToolsExt.Add("odt")

  stxToolsName.Add("ODT>EPUB")
  stxToolsDesc.Add(("Convertir documentos") & " ODT " & ("en") & " EPUB")
  stxToolsExt.Add("odt")

  '##PDF
  stxToolsName.Add("PDF>Decrypt")
  stxToolsDesc.Add(("Crea una copia desencriptada del archivo"))
  stxToolsExt.Add("pdf")

  stxToolsName.Add("PDF>Image")
  stxToolsDesc.Add(("Extractor de paginas en formato de imagen jpeg una imagen por página."))
  stxToolsExt.Add("pdf")

  stxToolsName.Add("PDF>Pages")
  stxToolsDesc.Add(("Extractor de paginas") & "PDF")
  stxToolsExt.Add("pdf")

  stxToolsName.Add("PDF>OCR-Text")
  stxToolsDesc.Add(("Extractor de paginas") & "TIF ." & ("Reconocimiento optico de caracteres"))
  stxToolsExt.Add("pdf")

  stxToolsName.Add("PDF>PDF-R90")
  stxToolsDesc.Add(("Gira las paginas del archivo") & " 90º")
  stxToolsExt.Add("pdf")

  '## Video
  stxToolsName.Add("Video>Frame")
  stxToolsDesc.Add(("Extractor de fotograma de un video"))
  stxToolsExt.Add("avi:mov:m2ts:mp4:webm:ogv")

  '## MDB, ACCDB
  stxToolsName.Add("JET>SQL")
  stxToolsDesc.Add(("Crea los archivos") & "SQL" & ("para crear bases de datos") & " SQLite / PostgreSQL / MySQL")
  stxToolsExt.Add("mdb:accdb")

  '## MS-OUTLOOK PST
  stxToolsName.Add("PST>Mbox")
  stxToolsDesc.Add(("Crea archivos") & " MBX " & ("a partir de") & " PST")
  stxToolsExt.Add("pst")

  ' Agragar acá las nuevas herramientas de vonversión. #######
  ' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

End

Public Sub LoadHeaders()

  stxHeaders.Add(("Ruta"))
  stxHeaders.Add(("Directorio"))
  stxHeaders.Add(("Archivo"))
  stxHeaders.Add(("Extensión"))
  stxHeaders.Add(("Nombre"))
  stxHeaders.Add(("Tamaño"))
  stxHeaders.Add(("Tiempo"))
  'stxHeaders.Add("CRC32")
  stxHeaders.Add(("Versión"))
  stxHeaders.Add(("Páginas"))

End

Public Function Terminator() As Integer ''Funcion que guarda las configuraciones que se modificaron en el programa antes de cerrarlo.

  'Dim int As Integer
  'Dim strLang As String
  'Dim strValue As String

  ' Settings["Dictionaries/Path"] = stxProgram[7]
  ' Settings["Language/Input"] = stxProgram[4]
  '
  ' Settings["Program/Database-Engine"] = stxProgram[0]
  ' Settings["Program/Database-Host"] = stxProgram[1]
  ' Settings["Program/Database-Name"] = stxProgram[2]
  ' Settings["Program/Database-Path"] = stxProgram[3]
  ' Settings["Program/Language-Input"] = stxProgram[4]
  ' Settings["Program/Language-Input3"] = stxProgram[5]
  ' Settings["Program/Language-InputEng"] = stxProgram[6]
  ' Settings["Program/Language-InputDict"] = stxProgram[7]
  '
  ' Settings["Program/Language-Output"] = stxProgram[8]
  ' Settings["Program/Language-Output3"] = stxProgram[9]
  ' Settings["Program/Language-OutputEng"] = stxProgram[10]
  ' Settings["Program/Language-OutputDict"] = stxProgram[11]
  ' Settings["Program/Window"] = stxProgram[12]
  ' Settings["Program/Default-width"] = stxProgram[14]
  '
  ' Settings.Save

  ' Return 1

End
